"""Chord-based simplicial complexes, Euler characteristic, homology and orientability."""
from __future__ import annotations
from itertools import combinations
from fractions import Fraction
import numpy as np

__all__ = ["SimplicialComplex", "chord_complex", "generalized_tonnetz",
           "trichord_classes", "rank_mod2", "rank_rational", "classify_surface"]


def rank_mod2(M):
    """Rank of an integer matrix over GF(2) (Gaussian elimination on bit rows)."""
    M = (np.array(M, dtype=np.int64) % 2).astype(np.uint8)
    if M.size == 0:
        return 0
    M = M.copy(); r = 0
    rows, cols = M.shape
    for c in range(cols):
        piv = next((i for i in range(r, rows) if M[i, c]), None)
        if piv is None:
            continue
        M[[r, piv]] = M[[piv, r]]
        for i in range(rows):
            if i != r and M[i, c]:
                M[i] ^= M[r]
        r += 1
        if r == rows:
            break
    return r


def rank_rational(M):
    """Exact rank over Q using fractions (matrices here are tiny)."""
    A = [[Fraction(int(x)) for x in row] for row in np.array(M, dtype=np.int64)]
    if not A or not A[0]:
        return 0
    rows, cols, r = len(A), len(A[0]), 0
    for c in range(cols):
        piv = next((i for i in range(r, rows) if A[i][c] != 0), None)
        if piv is None:
            continue
        A[r], A[piv] = A[piv], A[r]
        for i in range(rows):
            if i != r and A[i][c] != 0:
                f = A[i][c] / A[r][c]
                A[i] = [a - f * b for a, b in zip(A[i], A[r])]
        r += 1
        if r == rows:
            break
    return r


class SimplicialComplex:
    """A 2-dimensional (abstract) simplicial or Delta-complex.

    faces : iterable of 3-tuples of vertex labels (triangles). Edges and vertices are
    generated by closure. Vertices may be any hashable labels."""

    def __init__(self, faces, extra_edges=(), extra_vertices=()):
        self.F = sorted({tuple(sorted(f)) for f in faces})
        E = {tuple(sorted(e)) for f in self.F for e in combinations(f, 2)}
        E |= {tuple(sorted(e)) for e in extra_edges}
        self.E = sorted(E)
        V = {v for e in self.E for v in e} | set(extra_vertices)
        self.V = sorted(V)

    # --- counts -------------------------------------------------------------
    @property
    def f_vector(self):
        return (len(self.V), len(self.E), len(self.F))

    def euler_characteristic(self):
        v, e, f = self.f_vector
        return v - e + f

    # --- boundary matrices ----------------------------------------------------
    def _d1(self):
        vi = {v: i for i, v in enumerate(self.V)}
        D = np.zeros((len(self.V), len(self.E)), dtype=np.int64)
        for j, (a, b) in enumerate(self.E):
            D[vi[a], j] -= 1; D[vi[b], j] += 1
        return D

    def _d2(self):
        ei = {e: i for i, e in enumerate(self.E)}
        D = np.zeros((len(self.E), len(self.F)), dtype=np.int64)
        for j, (a, b, c) in enumerate(self.F):
            D[ei[(b, c)], j] += 1; D[ei[(a, c)], j] -= 1; D[ei[(a, b)], j] += 1
        return D

    def betti(self, field="Q"):
        """Betti numbers (b0, b1, b2) over Q or GF(2)."""
        rk = rank_rational if field == "Q" else rank_mod2
        r1, r2 = rk(self._d1()), rk(self._d2())
        v, e, f = self.f_vector
        return (v - r1, e - r1 - r2, f - r2)

    # --- local structure -------------------------------------------------------
    def edge_degrees(self):
        """How many triangles contain each edge."""
        deg = {e: 0 for e in self.E}
        for f in self.F:
            for e in combinations(f, 2):
                deg[tuple(sorted(e))] += 1
        return deg

    def is_pseudomanifold(self):
        """Every edge lies in exactly two triangles (closed) or at most two (with boundary)."""
        d = self.edge_degrees().values()
        return max(d) <= 2

    def vertex_links_are_cycles(self):
        """For a closed surface each vertex link must be a single cycle."""
        import networkx as nx
        for v in self.V:
            G = nx.Graph()
            for f in self.F:
                if v in f:
                    a, b = [x for x in f if x != v]
                    G.add_edge(a, b)
            if G.number_of_nodes() == 0:
                return False
            if not (nx.is_connected(G) and all(d == 2 for _, d in G.degree())):
                return False
        return True

    def is_orientable(self):
        """Try to orient all triangles coherently (valid when edges have degree <= 2)."""
        if not self.is_pseudomanifold():
            return None
        from collections import deque
        # orientation of a triangle = cyclic order; represent by +1/-1 relative to sorted order
        edge_tris = {}
        for i, f in enumerate(self.F):
            for e in combinations(f, 2):
                edge_tris.setdefault(tuple(sorted(e)), []).append(i)

        def induced(f, s):  # oriented edges of triangle f with sign s
            a, b, c = f
            es = [(a, b), (b, c), (c, a)]
            return es if s > 0 else [(y, x) for x, y in es]
        sign = {}
        for root in range(len(self.F)):
            if root in sign:
                continue
            sign[root] = 1
            q = deque([root])
            while q:
                i = q.popleft()
                for (x, y) in induced(self.F[i], sign[i]):
                    for j in edge_tris[tuple(sorted((x, y)))]:
                        if j == i:
                            continue
                        # neighbour must traverse the shared edge as (y, x)
                        need = 1 if (y, x) in induced(self.F[j], 1) else -1
                        if j not in sign:
                            sign[j] = need; q.append(j)
                        elif sign[j] != need:
                            return False
        return True

    def summary(self):
        v, e, f = self.f_vector
        return dict(V=v, E=e, F=f, chi=v - e + f, betti_Q=self.betti("Q"),
                    betti_Z2=self.betti("Z2"), max_edge_degree=max(self.edge_degrees().values()),
                    orientable=self.is_orientable())


def classify_surface(K: SimplicialComplex) -> str:
    """Name a connected closed surface from (chi, orientability); otherwise describe."""
    s = K.summary()
    if s["betti_Q"][0] != 1:
        return f"{s['betti_Q'][0]} components"
    if s["max_edge_degree"] > 2:
        return "not a surface (some edge in >2 triangles)"
    boundary = any(d == 1 for d in K.edge_degrees().values())
    chi, orient = s["chi"], s["orientable"]
    if boundary:
        if chi == 0:
            return "annulus (cylinder)" if orient else "Moebius band"
        return f"surface with boundary, chi={chi}, {'orientable' if orient else 'non-orientable'}"
    if not K.vertex_links_are_cycles():
        return "pseudo-surface (singular vertices)"
    if orient:
        g = (2 - chi) / 2
        return {0: "sphere", 1: "torus"}.get(g, f"orientable surface of genus {g:g}")
    k = 2 - chi
    return {1: "real projective plane", 2: "Klein bottle"}.get(k, f"connected sum of {k} projective planes")


def trichord_classes(n=12):
    """Interval partitions (a, b, c), a+b+c = n, up to rotation (i.e. T-classes) —
    Catanzaro's C(n1, n2, n3). Returns list of tuples."""
    seen, out = set(), []
    for a in range(1, n):
        for b in range(1, n - a):
            c = n - a - b
            key = min((a, b, c), (b, c, a), (c, a, b))
            if key not in seen:
                seen.add(key); out.append(key)
    return out


def chord_complex(chords, n=12):
    """Complex whose triangles are the given 3-note pitch-class sets."""
    return SimplicialComplex([tuple(sorted(p % n for p in ch)) for ch in chords
                              if len({p % n for p in ch}) == 3])


def generalized_tonnetz(a, b, c=None, n=12, with_inversions=True):
    """Catanzaro's generalized Tonnetz C(a,b,c) in Z_n: all transpositions (and, by
    default, inversions) of the trichord {0, a, a+b}."""
    c = n - a - b if c is None else c
    assert a + b + c == n
    base = {0, a % n, (a + b) % n}
    chords = set()
    for t in range(n):
        chords.add(frozenset((x + t) % n for x in base))
        if with_inversions:
            chords.add(frozenset((t - x) % n for x in base))
    chords = [ch for ch in chords if len(ch) == 3]
    return chord_complex(chords, n)
